// Code generated by protoc-gen-go.
// source: protos/broker.proto
// DO NOT EDIT!

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	protos/broker.proto

It has these top-level messages:
	Empty
	AuthToken
	InstrumentID
	InstrumentIDList
	Instrument
	InstrumentList
	AccountID
	Account
	AccountList
	Quote
	QuoteList
	OrderID
	Order
	OrderList
	OrderCreation
	OrderChange
	OrderCreationResponse
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OrderSide int32

const (
	OrderSide_BUY  OrderSide = 0
	OrderSide_SELL OrderSide = 1
)

var OrderSide_name = map[int32]string{
	0: "BUY",
	1: "SELL",
}
var OrderSide_value = map[string]int32{
	"BUY":  0,
	"SELL": 1,
}

func (x OrderSide) String() string {
	return proto.EnumName(OrderSide_name, int32(x))
}
func (OrderSide) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type OrderType int32

const (
	OrderType_LIMIT             OrderType = 0
	OrderType_STOP              OrderType = 1
	OrderType_MARKET_IF_TOUCHED OrderType = 2
	OrderType_MARKET            OrderType = 3
)

var OrderType_name = map[int32]string{
	0: "LIMIT",
	1: "STOP",
	2: "MARKET_IF_TOUCHED",
	3: "MARKET",
}
var OrderType_value = map[string]int32{
	"LIMIT":             0,
	"STOP":              1,
	"MARKET_IF_TOUCHED": 2,
	"MARKET":            3,
}

func (x OrderType) String() string {
	return proto.EnumName(OrderType_name, int32(x))
}
func (OrderType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type AuthToken struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *AuthToken) Reset()                    { *m = AuthToken{} }
func (m *AuthToken) String() string            { return proto.CompactTextString(m) }
func (*AuthToken) ProtoMessage()               {}
func (*AuthToken) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type InstrumentID struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *InstrumentID) Reset()                    { *m = InstrumentID{} }
func (m *InstrumentID) String() string            { return proto.CompactTextString(m) }
func (*InstrumentID) ProtoMessage()               {}
func (*InstrumentID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type InstrumentIDList struct {
	Value []*InstrumentID `protobuf:"bytes,1,rep,name=value" json:"value,omitempty"`
}

func (m *InstrumentIDList) Reset()                    { *m = InstrumentIDList{} }
func (m *InstrumentIDList) String() string            { return proto.CompactTextString(m) }
func (*InstrumentIDList) ProtoMessage()               {}
func (*InstrumentIDList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *InstrumentIDList) GetValue() []*InstrumentID {
	if m != nil {
		return m.Value
	}
	return nil
}

type Instrument struct {
	Name          string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	DisplayName   string `protobuf:"bytes,2,opt,name=display_name,json=displayName" json:"display_name,omitempty"`
	Pip           string `protobuf:"bytes,3,opt,name=pip" json:"pip,omitempty"`
	MaxTradeUnits int32  `protobuf:"varint,4,opt,name=max_trade_units,json=maxTradeUnits" json:"max_trade_units,omitempty"`
}

func (m *Instrument) Reset()                    { *m = Instrument{} }
func (m *Instrument) String() string            { return proto.CompactTextString(m) }
func (*Instrument) ProtoMessage()               {}
func (*Instrument) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type InstrumentList struct {
	Value []*Instrument `protobuf:"bytes,1,rep,name=value" json:"value,omitempty"`
}

func (m *InstrumentList) Reset()                    { *m = InstrumentList{} }
func (m *InstrumentList) String() string            { return proto.CompactTextString(m) }
func (*InstrumentList) ProtoMessage()               {}
func (*InstrumentList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *InstrumentList) GetValue() []*Instrument {
	if m != nil {
		return m.Value
	}
	return nil
}

type AccountID struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *AccountID) Reset()                    { *m = AccountID{} }
func (m *AccountID) String() string            { return proto.CompactTextString(m) }
func (*AccountID) ProtoMessage()               {}
func (*AccountID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type Account struct {
	Id           string  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name         string  `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Currency     string  `protobuf:"bytes,3,opt,name=currency" json:"currency,omitempty"`
	MarginRate   float64 `protobuf:"fixed64,4,opt,name=margin_rate,json=marginRate" json:"margin_rate,omitempty"`
	Balance      float64 `protobuf:"fixed64,5,opt,name=balance" json:"balance,omitempty"`
	UnrealizedPl float64 `protobuf:"fixed64,6,opt,name=unrealized_pl,json=unrealizedPl" json:"unrealized_pl,omitempty"`
	RealizedPl   float64 `protobuf:"fixed64,7,opt,name=realized_pl,json=realizedPl" json:"realized_pl,omitempty"`
	MarginUsed   float64 `protobuf:"fixed64,8,opt,name=margin_used,json=marginUsed" json:"margin_used,omitempty"`
	MarginAvail  float64 `protobuf:"fixed64,9,opt,name=margin_avail,json=marginAvail" json:"margin_avail,omitempty"`
	OpenTrades   float64 `protobuf:"fixed64,10,opt,name=open_trades,json=openTrades" json:"open_trades,omitempty"`
	OpenOrders   float64 `protobuf:"fixed64,11,opt,name=open_orders,json=openOrders" json:"open_orders,omitempty"`
}

func (m *Account) Reset()                    { *m = Account{} }
func (m *Account) String() string            { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()               {}
func (*Account) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type AccountList struct {
	Value []*Account `protobuf:"bytes,1,rep,name=value" json:"value,omitempty"`
}

func (m *AccountList) Reset()                    { *m = AccountList{} }
func (m *AccountList) String() string            { return proto.CompactTextString(m) }
func (*AccountList) ProtoMessage()               {}
func (*AccountList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *AccountList) GetValue() []*Account {
	if m != nil {
		return m.Value
	}
	return nil
}

type Quote struct {
	Name   string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Time   string  `protobuf:"bytes,2,opt,name=time" json:"time,omitempty"`
	Bid    float64 `protobuf:"fixed64,3,opt,name=bid" json:"bid,omitempty"`
	Ask    float64 `protobuf:"fixed64,4,opt,name=ask" json:"ask,omitempty"`
	Status string  `protobuf:"bytes,5,opt,name=status" json:"status,omitempty"`
}

func (m *Quote) Reset()                    { *m = Quote{} }
func (m *Quote) String() string            { return proto.CompactTextString(m) }
func (*Quote) ProtoMessage()               {}
func (*Quote) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type QuoteList struct {
	Value []*Quote `protobuf:"bytes,1,rep,name=value" json:"value,omitempty"`
}

func (m *QuoteList) Reset()                    { *m = QuoteList{} }
func (m *QuoteList) String() string            { return proto.CompactTextString(m) }
func (*QuoteList) ProtoMessage()               {}
func (*QuoteList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *QuoteList) GetValue() []*Quote {
	if m != nil {
		return m.Value
	}
	return nil
}

type OrderID struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *OrderID) Reset()                    { *m = OrderID{} }
func (m *OrderID) String() string            { return proto.CompactTextString(m) }
func (*OrderID) ProtoMessage()               {}
func (*OrderID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type Order struct {
	Id           string    `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Instrument   string    `protobuf:"bytes,2,opt,name=instrument" json:"instrument,omitempty"`
	Units        int32     `protobuf:"varint,3,opt,name=units" json:"units,omitempty"`
	Side         OrderSide `protobuf:"varint,4,opt,name=side,enum=protos.OrderSide" json:"side,omitempty"`
	Type         OrderType `protobuf:"varint,5,opt,name=type,enum=protos.OrderType" json:"type,omitempty"`
	Time         string    `protobuf:"bytes,6,opt,name=time" json:"time,omitempty"`
	Price        float64   `protobuf:"fixed64,7,opt,name=price" json:"price,omitempty"`
	TakeProfit   float64   `protobuf:"fixed64,8,opt,name=take_profit,json=takeProfit" json:"take_profit,omitempty"`
	StopLoss     float64   `protobuf:"fixed64,9,opt,name=stop_loss,json=stopLoss" json:"stop_loss,omitempty"`
	Expiry       string    `protobuf:"bytes,10,opt,name=expiry" json:"expiry,omitempty"`
	UpperBound   float64   `protobuf:"fixed64,11,opt,name=upper_bound,json=upperBound" json:"upper_bound,omitempty"`
	LowerBound   float64   `protobuf:"fixed64,12,opt,name=lower_bound,json=lowerBound" json:"lower_bound,omitempty"`
	TrailingStop float64   `protobuf:"fixed64,13,opt,name=trailing_stop,json=trailingStop" json:"trailing_stop,omitempty"`
}

func (m *Order) Reset()                    { *m = Order{} }
func (m *Order) String() string            { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()               {}
func (*Order) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type OrderList struct {
	Value []*Order `protobuf:"bytes,1,rep,name=value" json:"value,omitempty"`
}

func (m *OrderList) Reset()                    { *m = OrderList{} }
func (m *OrderList) String() string            { return proto.CompactTextString(m) }
func (*OrderList) ProtoMessage()               {}
func (*OrderList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *OrderList) GetValue() []*Order {
	if m != nil {
		return m.Value
	}
	return nil
}

type OrderCreation struct {
	Instrument   string     `protobuf:"bytes,1,opt,name=instrument" json:"instrument,omitempty"`
	Units        int32      `protobuf:"varint,2,opt,name=units" json:"units,omitempty"`
	Side         OrderSide  `protobuf:"varint,3,opt,name=side,enum=protos.OrderSide" json:"side,omitempty"`
	Type         OrderType  `protobuf:"varint,4,opt,name=type,enum=protos.OrderType" json:"type,omitempty"`
	Expiry       string     `protobuf:"bytes,5,opt,name=expiry" json:"expiry,omitempty"`
	Price        float64    `protobuf:"fixed64,6,opt,name=price" json:"price,omitempty"`
	TakeProfit   float64    `protobuf:"fixed64,7,opt,name=take_profit,json=takeProfit" json:"take_profit,omitempty"`
	StopLoss     float64    `protobuf:"fixed64,8,opt,name=stop_loss,json=stopLoss" json:"stop_loss,omitempty"`
	UpperBound   float64    `protobuf:"fixed64,9,opt,name=upper_bound,json=upperBound" json:"upper_bound,omitempty"`
	LowerBound   float64    `protobuf:"fixed64,10,opt,name=lower_bound,json=lowerBound" json:"lower_bound,omitempty"`
	TrailingStop float64    `protobuf:"fixed64,11,opt,name=trailing_stop,json=trailingStop" json:"trailing_stop,omitempty"`
	AccountId    *AccountID `protobuf:"bytes,12,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
}

func (m *OrderCreation) Reset()                    { *m = OrderCreation{} }
func (m *OrderCreation) String() string            { return proto.CompactTextString(m) }
func (*OrderCreation) ProtoMessage()               {}
func (*OrderCreation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *OrderCreation) GetAccountId() *AccountID {
	if m != nil {
		return m.AccountId
	}
	return nil
}

type OrderChange struct {
	Units        int32      `protobuf:"varint,1,opt,name=units" json:"units,omitempty"`
	Price        float64    `protobuf:"fixed64,2,opt,name=price" json:"price,omitempty"`
	Expiry       string     `protobuf:"bytes,3,opt,name=expiry" json:"expiry,omitempty"`
	TakeProfit   float64    `protobuf:"fixed64,4,opt,name=take_profit,json=takeProfit" json:"take_profit,omitempty"`
	StopLoss     float64    `protobuf:"fixed64,5,opt,name=stop_loss,json=stopLoss" json:"stop_loss,omitempty"`
	UpperBound   float64    `protobuf:"fixed64,6,opt,name=upper_bound,json=upperBound" json:"upper_bound,omitempty"`
	LowerBound   float64    `protobuf:"fixed64,7,opt,name=lower_bound,json=lowerBound" json:"lower_bound,omitempty"`
	TrailingStop float64    `protobuf:"fixed64,8,opt,name=trailing_stop,json=trailingStop" json:"trailing_stop,omitempty"`
	AccountId    *AccountID `protobuf:"bytes,9,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	OrderId      *OrderID   `protobuf:"bytes,10,opt,name=order_id,json=orderId" json:"order_id,omitempty"`
}

func (m *OrderChange) Reset()                    { *m = OrderChange{} }
func (m *OrderChange) String() string            { return proto.CompactTextString(m) }
func (*OrderChange) ProtoMessage()               {}
func (*OrderChange) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *OrderChange) GetAccountId() *AccountID {
	if m != nil {
		return m.AccountId
	}
	return nil
}

func (m *OrderChange) GetOrderId() *OrderID {
	if m != nil {
		return m.OrderId
	}
	return nil
}

type OrderCreationResponse struct {
	Time  string `protobuf:"bytes,1,opt,name=time" json:"time,omitempty"`
	Order *Order `protobuf:"bytes,2,opt,name=order" json:"order,omitempty"`
}

func (m *OrderCreationResponse) Reset()                    { *m = OrderCreationResponse{} }
func (m *OrderCreationResponse) String() string            { return proto.CompactTextString(m) }
func (*OrderCreationResponse) ProtoMessage()               {}
func (*OrderCreationResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *OrderCreationResponse) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "protos.Empty")
	proto.RegisterType((*AuthToken)(nil), "protos.AuthToken")
	proto.RegisterType((*InstrumentID)(nil), "protos.InstrumentID")
	proto.RegisterType((*InstrumentIDList)(nil), "protos.InstrumentIDList")
	proto.RegisterType((*Instrument)(nil), "protos.Instrument")
	proto.RegisterType((*InstrumentList)(nil), "protos.InstrumentList")
	proto.RegisterType((*AccountID)(nil), "protos.AccountID")
	proto.RegisterType((*Account)(nil), "protos.Account")
	proto.RegisterType((*AccountList)(nil), "protos.AccountList")
	proto.RegisterType((*Quote)(nil), "protos.Quote")
	proto.RegisterType((*QuoteList)(nil), "protos.QuoteList")
	proto.RegisterType((*OrderID)(nil), "protos.OrderID")
	proto.RegisterType((*Order)(nil), "protos.Order")
	proto.RegisterType((*OrderList)(nil), "protos.OrderList")
	proto.RegisterType((*OrderCreation)(nil), "protos.OrderCreation")
	proto.RegisterType((*OrderChange)(nil), "protos.OrderChange")
	proto.RegisterType((*OrderCreationResponse)(nil), "protos.OrderCreationResponse")
	proto.RegisterEnum("protos.OrderSide", OrderSide_name, OrderSide_value)
	proto.RegisterEnum("protos.OrderType", OrderType_name, OrderType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Broker service

type BrokerClient interface {
	GetInstrumentList(ctx context.Context, in *AuthToken, opts ...grpc.CallOption) (*InstrumentList, error)
	GetPrices(ctx context.Context, in *InstrumentIDList, opts ...grpc.CallOption) (*QuoteList, error)
	StreamQuotes(ctx context.Context, in *InstrumentID, opts ...grpc.CallOption) (Broker_StreamQuotesClient, error)
	GetAccounts(ctx context.Context, in *AuthToken, opts ...grpc.CallOption) (*AccountList, error)
	GetOrders(ctx context.Context, in *AccountID, opts ...grpc.CallOption) (*OrderList, error)
	CreateOrder(ctx context.Context, in *OrderCreation, opts ...grpc.CallOption) (*OrderCreationResponse, error)
	ChangeOrder(ctx context.Context, in *OrderChange, opts ...grpc.CallOption) (*Order, error)
}

type brokerClient struct {
	cc *grpc.ClientConn
}

func NewBrokerClient(cc *grpc.ClientConn) BrokerClient {
	return &brokerClient{cc}
}

func (c *brokerClient) GetInstrumentList(ctx context.Context, in *AuthToken, opts ...grpc.CallOption) (*InstrumentList, error) {
	out := new(InstrumentList)
	err := grpc.Invoke(ctx, "/protos.Broker/GetInstrumentList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) GetPrices(ctx context.Context, in *InstrumentIDList, opts ...grpc.CallOption) (*QuoteList, error) {
	out := new(QuoteList)
	err := grpc.Invoke(ctx, "/protos.Broker/GetPrices", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) StreamQuotes(ctx context.Context, in *InstrumentID, opts ...grpc.CallOption) (Broker_StreamQuotesClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Broker_serviceDesc.Streams[0], c.cc, "/protos.Broker/StreamQuotes", opts...)
	if err != nil {
		return nil, err
	}
	x := &brokerStreamQuotesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Broker_StreamQuotesClient interface {
	Recv() (*Quote, error)
	grpc.ClientStream
}

type brokerStreamQuotesClient struct {
	grpc.ClientStream
}

func (x *brokerStreamQuotesClient) Recv() (*Quote, error) {
	m := new(Quote)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *brokerClient) GetAccounts(ctx context.Context, in *AuthToken, opts ...grpc.CallOption) (*AccountList, error) {
	out := new(AccountList)
	err := grpc.Invoke(ctx, "/protos.Broker/GetAccounts", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) GetOrders(ctx context.Context, in *AccountID, opts ...grpc.CallOption) (*OrderList, error) {
	out := new(OrderList)
	err := grpc.Invoke(ctx, "/protos.Broker/GetOrders", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) CreateOrder(ctx context.Context, in *OrderCreation, opts ...grpc.CallOption) (*OrderCreationResponse, error) {
	out := new(OrderCreationResponse)
	err := grpc.Invoke(ctx, "/protos.Broker/CreateOrder", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) ChangeOrder(ctx context.Context, in *OrderChange, opts ...grpc.CallOption) (*Order, error) {
	out := new(Order)
	err := grpc.Invoke(ctx, "/protos.Broker/ChangeOrder", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Broker service

type BrokerServer interface {
	GetInstrumentList(context.Context, *AuthToken) (*InstrumentList, error)
	GetPrices(context.Context, *InstrumentIDList) (*QuoteList, error)
	StreamQuotes(*InstrumentID, Broker_StreamQuotesServer) error
	GetAccounts(context.Context, *AuthToken) (*AccountList, error)
	GetOrders(context.Context, *AccountID) (*OrderList, error)
	CreateOrder(context.Context, *OrderCreation) (*OrderCreationResponse, error)
	ChangeOrder(context.Context, *OrderChange) (*Order, error)
}

func RegisterBrokerServer(s *grpc.Server, srv BrokerServer) {
	s.RegisterService(&_Broker_serviceDesc, srv)
}

func _Broker_GetInstrumentList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).GetInstrumentList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Broker/GetInstrumentList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).GetInstrumentList(ctx, req.(*AuthToken))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_GetPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstrumentIDList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).GetPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Broker/GetPrices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).GetPrices(ctx, req.(*InstrumentIDList))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_StreamQuotes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InstrumentID)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BrokerServer).StreamQuotes(m, &brokerStreamQuotesServer{stream})
}

type Broker_StreamQuotesServer interface {
	Send(*Quote) error
	grpc.ServerStream
}

type brokerStreamQuotesServer struct {
	grpc.ServerStream
}

func (x *brokerStreamQuotesServer) Send(m *Quote) error {
	return x.ServerStream.SendMsg(m)
}

func _Broker_GetAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).GetAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Broker/GetAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).GetAccounts(ctx, req.(*AuthToken))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_GetOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).GetOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Broker/GetOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).GetOrders(ctx, req.(*AccountID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderCreation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Broker/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).CreateOrder(ctx, req.(*OrderCreation))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_ChangeOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderChange)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).ChangeOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Broker/ChangeOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).ChangeOrder(ctx, req.(*OrderChange))
	}
	return interceptor(ctx, in, info, handler)
}

var _Broker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Broker",
	HandlerType: (*BrokerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInstrumentList",
			Handler:    _Broker_GetInstrumentList_Handler,
		},
		{
			MethodName: "GetPrices",
			Handler:    _Broker_GetPrices_Handler,
		},
		{
			MethodName: "GetAccounts",
			Handler:    _Broker_GetAccounts_Handler,
		},
		{
			MethodName: "GetOrders",
			Handler:    _Broker_GetOrders_Handler,
		},
		{
			MethodName: "CreateOrder",
			Handler:    _Broker_CreateOrder_Handler,
		},
		{
			MethodName: "ChangeOrder",
			Handler:    _Broker_ChangeOrder_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamQuotes",
			Handler:       _Broker_StreamQuotes_Handler,
			ServerStreams: true,
		},
	},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("protos/broker.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1041 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x56, 0xdd, 0x6e, 0xe3, 0x44,
	0x18, 0x6d, 0xe2, 0xfc, 0xf9, 0x73, 0xd2, 0xa6, 0xd3, 0xed, 0xca, 0x0a, 0x62, 0x97, 0xf5, 0x02,
	0xaa, 0x7a, 0xb1, 0x54, 0x5d, 0x24, 0xa4, 0xbd, 0x40, 0xb4, 0xdd, 0x00, 0x11, 0x59, 0x1a, 0xdc,
	0xf4, 0x82, 0x2b, 0xcb, 0x49, 0x4c, 0xd7, 0xaa, 0x63, 0x5b, 0x9e, 0xf1, 0xd2, 0x20, 0x71, 0xc3,
	0x53, 0xf0, 0x0a, 0xbc, 0x0d, 0x17, 0x3c, 0x10, 0x33, 0xdf, 0x8c, 0x63, 0x3b, 0x49, 0x93, 0xbd,
	0xf3, 0x9c, 0xef, 0xcc, 0xcc, 0x37, 0xe7, 0x9c, 0xb1, 0x0d, 0x47, 0x71, 0x12, 0xb1, 0x88, 0x7e,
	0x35, 0x49, 0xa2, 0x7b, 0x2f, 0x79, 0x85, 0x23, 0xd2, 0x90, 0xa0, 0xd5, 0x84, 0x7a, 0x7f, 0x1e,
	0xb3, 0x85, 0xf5, 0x02, 0xf4, 0x8b, 0x94, 0xbd, 0x1f, 0x73, 0x4e, 0x48, 0x9e, 0x40, 0xfd, 0x83,
	0x1b, 0xa4, 0x9e, 0x59, 0xf9, 0xac, 0x72, 0xa2, 0xdb, 0x72, 0x60, 0x7d, 0x0e, 0xed, 0x41, 0x48,
	0x59, 0x92, 0xce, 0xbd, 0x90, 0x0d, 0xde, 0x3e, 0xc2, 0xfa, 0x16, 0xba, 0x45, 0xd6, 0xd0, 0xa7,
	0x8c, 0x9c, 0xe6, 0x4c, 0xed, 0xc4, 0x38, 0x7f, 0x22, 0x9b, 0xa0, 0xaf, 0x8a, 0xc4, 0x6c, 0xfe,
	0x9f, 0x00, 0x39, 0x4c, 0x08, 0xd4, 0x42, 0x77, 0x9e, 0x6d, 0x81, 0xcf, 0xe4, 0x05, 0xb4, 0x67,
	0x3e, 0x8d, 0x03, 0x77, 0xe1, 0x60, 0xad, 0x8a, 0x35, 0x43, 0x61, 0x3f, 0x0b, 0x4a, 0x17, 0xb4,
	0xd8, 0x8f, 0x4d, 0x0d, 0x2b, 0xe2, 0x91, 0x7c, 0x09, 0x07, 0x73, 0xf7, 0xc1, 0x61, 0x89, 0x3b,
	0xf3, 0x9c, 0x34, 0xf4, 0x19, 0x35, 0x6b, 0xbc, 0x5a, 0xb7, 0x3b, 0x1c, 0x1e, 0x0b, 0xf4, 0x56,
	0x80, 0xd6, 0x1b, 0xd8, 0xcf, 0xb7, 0xc7, 0xe6, 0x4f, 0xca, 0xcd, 0x93, 0xf5, 0xe6, 0xb3, 0xd6,
	0x85, 0x86, 0xd3, 0x69, 0x94, 0x6e, 0x51, 0xe7, 0xdf, 0x2a, 0x34, 0x15, 0x87, 0xec, 0x43, 0xd5,
	0x9f, 0xa9, 0x32, 0x7f, 0x5a, 0x9e, 0xb5, 0x5a, 0x38, 0x6b, 0x0f, 0x5a, 0xd3, 0x34, 0x49, 0xbc,
	0x70, 0xba, 0x50, 0xa7, 0x59, 0x8e, 0xc9, 0x73, 0x30, 0xe6, 0x6e, 0x72, 0xe7, 0x87, 0x4e, 0xe2,
	0x32, 0x0f, 0x8f, 0x53, 0xb1, 0x41, 0x42, 0x36, 0x47, 0x88, 0x09, 0xcd, 0x89, 0x1b, 0xb8, 0xe1,
	0xd4, 0x33, 0xeb, 0x58, 0xcc, 0x86, 0xe4, 0x25, 0x74, 0xd2, 0x30, 0xf1, 0xdc, 0xc0, 0xff, 0xc3,
	0x9b, 0x39, 0x71, 0x60, 0x36, 0xb0, 0xde, 0xce, 0xc1, 0x51, 0x20, 0xd6, 0x2f, 0x52, 0x9a, 0x72,
	0xfd, 0x32, 0x41, 0x35, 0x90, 0x52, 0x6f, 0x66, 0xb6, 0x8a, 0x0d, 0xdc, 0x72, 0x44, 0x38, 0xa5,
	0x08, 0xee, 0x07, 0xd7, 0x0f, 0x4c, 0x1d, 0x19, 0x6a, 0xd2, 0x85, 0x80, 0xc4, 0x1a, 0x51, 0xec,
	0x85, 0xd2, 0x18, 0x6a, 0x82, 0x5c, 0x43, 0x40, 0x68, 0x0a, 0x5d, 0x12, 0xa2, 0x64, 0xe6, 0x25,
	0xd4, 0x34, 0x72, 0xc2, 0x35, 0x22, 0xd6, 0xd7, 0x60, 0x28, 0x45, 0xd1, 0xae, 0x2f, 0xca, 0x76,
	0x1d, 0x64, 0x76, 0x29, 0x4e, 0x66, 0xc4, 0x3d, 0xd4, 0x7f, 0x49, 0x23, 0x2e, 0xd2, 0xa6, 0x84,
	0x71, 0x8c, 0xf9, 0xb9, 0x13, 0xe2, 0x59, 0x44, 0x6a, 0xc2, 0xed, 0xd2, 0x70, 0x7f, 0xf1, 0x28,
	0x10, 0x97, 0xde, 0x2b, 0xdd, 0xc5, 0x23, 0x79, 0x0a, 0x0d, 0xca, 0x5c, 0x96, 0x52, 0xd4, 0x5b,
	0xb7, 0xd5, 0xc8, 0x3a, 0x03, 0x1d, 0x37, 0xc3, 0x06, 0x5f, 0x96, 0x1b, 0xec, 0x64, 0x0d, 0x22,
	0x23, 0x6b, 0xef, 0x39, 0x34, 0xf1, 0x78, 0x8f, 0x06, 0xe9, 0x2f, 0x0d, 0xea, 0xc8, 0x58, 0x8b,
	0xd1, 0x33, 0x00, 0x7f, 0x19, 0x4d, 0x75, 0x84, 0x02, 0x22, 0xd6, 0x93, 0xf9, 0xd7, 0x30, 0xff,
	0x72, 0xc0, 0x65, 0xab, 0x51, 0x7f, 0x26, 0x53, 0xb4, 0x7f, 0x7e, 0x98, 0x35, 0x85, 0x5b, 0xdc,
	0xf0, 0x82, 0x8d, 0x65, 0x41, 0x63, 0x8b, 0x58, 0xe6, 0x69, 0x95, 0x36, 0xe6, 0x05, 0x1b, 0xcb,
	0x4b, 0x01, 0x1b, 0x05, 0x01, 0xf9, 0xbe, 0x71, 0xe2, 0xf3, 0x2c, 0xca, 0x20, 0xc9, 0x81, 0xb0,
	0x97, 0xb9, 0xf7, 0x9e, 0xc3, 0x17, 0xfa, 0xcd, 0x67, 0x59, 0x86, 0x04, 0x34, 0x42, 0x84, 0x7c,
	0x02, 0x3a, 0x65, 0x51, 0xec, 0x04, 0x11, 0xa5, 0x2a, 0x40, 0x2d, 0x01, 0x0c, 0xf9, 0x58, 0x08,
	0xee, 0x3d, 0xc4, 0x7e, 0xb2, 0xc0, 0xe0, 0x70, 0xc1, 0xe5, 0x48, 0xac, 0x9a, 0xc6, 0xb1, 0x97,
	0x38, 0x13, 0xee, 0xf9, 0x2c, 0x0b, 0x0d, 0x42, 0x97, 0x02, 0x11, 0x84, 0x20, 0xfa, 0x7d, 0x49,
	0x68, 0x4b, 0x02, 0x42, 0x92, 0xc0, 0x6f, 0x08, 0x8f, 0xa4, 0x1f, 0xf8, 0xe1, 0x9d, 0x23, 0xb6,
	0x33, 0x3b, 0xf2, 0x86, 0x64, 0xe0, 0x0d, 0xc7, 0x84, 0xaf, 0x78, 0xf2, 0xad, 0xbe, 0x22, 0x23,
	0xb3, 0xed, 0x6f, 0x0d, 0x3a, 0x08, 0x5c, 0xf1, 0x7b, 0xc4, 0xfc, 0x28, 0x5c, 0xb1, 0xab, 0xf2,
	0xb8, 0x5d, 0xd5, 0x4d, 0x76, 0x69, 0x1f, 0x67, 0x57, 0x6d, 0xbb, 0x5d, 0xb9, 0x8c, 0xf5, 0x92,
	0x8c, 0x4b, 0xcb, 0x1a, 0x5b, 0x2c, 0x6b, 0x6e, 0xb7, 0xac, 0xb5, 0x62, 0xd9, 0x8a, 0x35, 0xfa,
	0x2e, 0x6b, 0x60, 0xb7, 0x35, 0xc6, 0xba, 0x35, 0xe4, 0x0c, 0xc0, 0x95, 0x37, 0xde, 0xf1, 0xa5,
	0xbf, 0x46, 0x7e, 0xfe, 0xe5, 0x5b, 0xda, 0xd6, 0x15, 0x69, 0x30, 0xb3, 0xfe, 0xab, 0x82, 0x21,
	0xad, 0x79, 0xef, 0x86, 0x77, 0x5e, 0x2e, 0x7c, 0xa5, 0x28, 0xfc, 0x52, 0x92, 0x6a, 0x51, 0x92,
	0x5c, 0x40, 0x6d, 0x35, 0x87, 0x45, 0xa9, 0x6a, 0xdb, 0xa5, 0xaa, 0x6f, 0x97, 0xaa, 0xb1, 0x4b,
	0xaa, 0xe6, 0x6e, 0xa9, 0x5a, 0x3b, 0xa5, 0xd2, 0x77, 0x4b, 0xc5, 0xbf, 0xe7, 0x2d, 0x7c, 0x1d,
	0x0b, 0x3e, 0x20, 0xff, 0xa0, 0x14, 0x2d, 0xce, 0x6e, 0x22, 0x81, 0xcb, 0x3a, 0x82, 0xe3, 0x52,
	0xe0, 0x6d, 0x8f, 0xc6, 0x51, 0x48, 0xf3, 0x77, 0x44, 0xa5, 0xf0, 0x8e, 0xe0, 0x77, 0x08, 0xe7,
	0xa1, 0xba, 0xeb, 0x77, 0x08, 0x6b, 0xa7, 0xcf, 0xd4, 0xad, 0x13, 0x39, 0x27, 0x4d, 0xd0, 0x2e,
	0x6f, 0x7f, 0xed, 0xee, 0x91, 0x16, 0xd4, 0x6e, 0xfa, 0xc3, 0x61, 0xb7, 0x72, 0x7a, 0xa5, 0xea,
	0x22, 0xe0, 0x44, 0x87, 0xfa, 0x70, 0xf0, 0x6e, 0x30, 0x56, 0x8c, 0xf1, 0xf5, 0xa8, 0x5b, 0x21,
	0xc7, 0x70, 0xf8, 0xee, 0xc2, 0xfe, 0xa9, 0x3f, 0x76, 0x06, 0xdf, 0x3b, 0xe3, 0xeb, 0xdb, 0xab,
	0x1f, 0xfb, 0x6f, 0xbb, 0x55, 0x02, 0xd0, 0x90, 0x70, 0x57, 0x3b, 0xff, 0x47, 0x83, 0xc6, 0x25,
	0xfe, 0x31, 0x91, 0xef, 0xe0, 0xf0, 0x07, 0x8f, 0xad, 0xfc, 0x15, 0xe4, 0x02, 0x65, 0x7f, 0x4d,
	0xbd, 0xa7, 0xeb, 0x7f, 0x06, 0x82, 0x6a, 0xed, 0x91, 0x37, 0xa0, 0xf3, 0x15, 0x46, 0x22, 0x2a,
	0x94, 0x98, 0x9b, 0xfe, 0x7e, 0x04, 0xb1, 0x77, 0x58, 0xfa, 0x14, 0xa8, 0xb9, 0xdf, 0x40, 0xfb,
	0x86, 0x71, 0xed, 0xe6, 0x08, 0xf2, 0x00, 0x6e, 0x9a, 0xde, 0x2b, 0x7f, 0x45, 0xac, 0xbd, 0xb3,
	0x0a, 0x9f, 0x68, 0xf0, 0x4d, 0x95, 0x7f, 0x74, 0x53, 0xc3, 0x47, 0x2b, 0x26, 0xab, 0x1d, 0x5f,
	0x63, 0xb7, 0xf2, 0xeb, 0x4a, 0xd6, 0x83, 0xd0, 0x2b, 0xbf, 0x46, 0xd4, 0xa4, 0x3e, 0x18, 0xe8,
	0xb0, 0x27, 0x3f, 0x4a, 0xc7, 0x25, 0x4e, 0xe6, 0x7d, 0xef, 0xd3, 0x8d, 0x70, 0x16, 0x09, 0xdc,
	0xdb, 0x90, 0xd7, 0x4f, 0x2e, 0x73, 0x54, 0xe6, 0x63, 0xa5, 0x57, 0x4e, 0x85, 0xb5, 0x37, 0x91,
	0x3f, 0xb3, 0xaf, 0xff, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x49, 0x14, 0x9e, 0x1b, 0xea, 0x0a, 0x00,
	0x00,
}
